spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_v2.8.1?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    poolMaxTotal: 10
    poolMaxIdle: 10
